@echo off
cd /d "%~dp0"
echo Starting CarbonLedger Platform...

echo 1. Starting Local Blockchain Node...
start cmd /k "cd /d "%~dp0contract" && npx hardhat node"

echo Waiting for blockchain node to boot up...
ping 127.0.0.1 -n 6 > nul

echo 2. Deploying Smart Contracts and Updating Backend Config...
start cmd /c "cd /d "%~dp0contract" && npx hardhat run scripts/deploy.js --network localhost && pause"

echo Waiting for contract deployment to complete...
ping 127.0.0.1 -n 6 > nul

echo 3. Starting Backend Express Server...
start cmd /k "cd /d "%~dp0Backend" && npm run dev"

echo 4. Starting Frontend Vite Application...
start cmd /k "cd /d "%~dp0frontend" && npm run dev"

echo All CarbonLedger services launched successfully!
