@echo off
echo Starting CarbonLedger Platform...

echo 1. Starting Local Blockchain...
start cmd /k "cd contract && npx hardhat node"

echo Waiting for blockchain to boot up...
timeout /t 5 /nobreak > nul

echo 2. Deploying Smart Contracts and Updating Backend Config...
start cmd /c "cd contract && npx hardhat run scripts/deploy.js --network localhost && pause"

echo Waiting for deployment to finish...
timeout /t 5 /nobreak > nul

echo 3. Starting Backend Server...
start cmd /k "cd Backend && npm start"

echo 4. Starting Frontend Application...
start cmd /k "cd frontend && npm run dev"

echo All services launched!
