import React from 'react'
import { AlertTriangle, BadgeCheck, BarChart3, Bell, BriefcaseBusiness, Building2, Check, ChevronRight, ClipboardCheck, CloudUpload, Coins, FileCheck2, FileText, Filter, Gauge, Globe2, Home, Leaf, ListChecks, Lock, LogOut, Menu, MessageSquare, Plus, Recycle, Search, Settings, ShieldCheck, ShoppingCart, SlidersHorizontal, Store, Upload, UserCheck, Wallet, X } from 'lucide-react'
import { apiGet, apiPost, clearSession, getStoredSession, setAuthToken, storeSession } from './utils/api.js'

const nav = [
  ['dashboard','Dashboard',Home], ['submit','Submit Project',Plus], ['projects','My Projects',BriefcaseBusiness], ['auditors','Hire Auditor',UserCheck], ['auditor','Auditor Queue',ClipboardCheck], ['review','Review Workspace',FileCheck2], ['wallet','Credits Wallet',Wallet], ['marketplace','Marketplace',Store], ['admin','Admin',ShieldCheck]
]
const fmt = (v) => new Intl.NumberFormat('en-US').format(v || 0)
const money = (v) => `$${Number(v || 0).toFixed(2)}`
function badge(status){ const s=String(status||'').toLowerCase(); if(['verified','minted','available','approved','retired'].includes(s)) return 'badge success'; if(['listed','sold'].includes(s)) return 'badge market'; if(s.includes('need')) return 'badge warning'; if(['rejected','failed'].includes(s)) return 'badge danger'; if(['assigned','pending'].includes(s)) return 'badge info'; return 'badge neutral' }
function errMsg(err){ return err?.response?.data?.err || err?.response?.data?.msg || err.message || 'Request failed' }

export default function App(){
  const [page,setPage]=React.useState('dashboard'), [role,setRole]=React.useState('user'), [user,setUser]=React.useState(null), [token,setToken]=React.useState(null)
  const [projects,setProjects]=React.useState([]), [credits,setCredits]=React.useState([]), [listings,setListings]=React.useState([]), [auditors,setAuditors]=React.useState([])
  const [selected,setSelected]=React.useState(''), [drawer,setDrawer]=React.useState(false), [toast,setToast]=React.useState(''), [mobile,setMobile]=React.useState(false), [health,setHealth]=React.useState(null), [loading,setLoading]=React.useState(false)
  const project = projects.find(p=>p.projectId===selected) || projects[0]
  const stats = { total:projects.length, active:projects.filter(p=>['Pending','Assigned','Need More Info'].includes(p.status)).length, minted:projects.filter(p=>p.status==='Minted').length, issued:credits.reduce((s,c)=>s+c.amount,0), listed:listings.reduce((s,l)=>s+l.amount,0), retired:credits.reduce((s,c)=>s+c.retired,0) }
  function note(msg){ setToast(msg); clearTimeout(window.__clToast); window.__clToast=setTimeout(()=>setToast(''),4200) }
  async function refresh(){ if(!token) return; setLoading(true); try{ const [ps,cs,ls,as,h]=await Promise.all([apiGet('/projects'),apiGet('/market/credits'),apiGet('/market/listings'),apiGet('/projects/auditors'),apiGet('/health')]); setProjects(ps.projects||[]); setCredits(cs.credits||[]); setListings(ls.listings||[]); setAuditors(as.auditors||[]); setHealth(h); if(!selected && ps.projects?.[0]) setSelected(ps.projects[0].projectId) }catch(e){ note(errMsg(e)) }finally{ setLoading(false) } }
  React.useEffect(()=>{ const saved=getStoredSession(); if(saved?.token){ setAuthToken(saved.token); setToken(saved.token); setUser(saved.user); setRole(saved.user?.role||'user') } },[])
  React.useEffect(()=>{ refresh() },[token])
  async function login(body){ const data=await apiPost('/auth/login',body); storeSession(data); setToken(data.token); setUser(data.user); setRole(data.user.role); setPage('dashboard'); note('Signed in successfully.'); }
  async function register(body){ const data=await apiPost('/auth/register',body); storeSession(data); setToken(data.token); setUser(data.user); setRole(data.user.role); setPage('dashboard'); note('Account created and signed in.'); }
  function logout(){ clearSession(); setToken(null); setUser(null); setProjects([]); setCredits([]); setListings([]); setAuditors([]); setPage('dashboard') }
  async function submitProject(form){ await apiPost('/projects',form); note('Project registered in MongoDB and on-chain.'); setPage('projects'); await refresh(); }
  async function hireAuditor(projectId,auditorId){ await apiPost(`/projects/${projectId}/hire-auditor`,{auditorId}); note('Auditor assigned in MongoDB and on-chain.'); await refresh(); }
  async function approve(projectId,approvedCredits){ await apiPost(`/audit/${projectId}/approve`,{approvedCredits}); note('Project approved and credits minted on-chain.'); await refresh(); }
  async function requestInfo(projectId,reason){ await apiPost(`/audit/${projectId}/more-info`,{reason}); note('More information requested.'); await refresh(); }
  async function reject(projectId,reason){ await apiPost(`/audit/${projectId}/reject`,{reason}); note('Project rejected.'); await refresh(); }
  async function listCredit(creditId,amount,price){ await apiPost('/market/list',{creditId,amount,price}); note('Credit listed in marketplace.'); await refresh(); }
  async function buy(listingId){ await apiPost(`/market/buy/${listingId}`,{}); note('Listing purchased and credit ownership updated.'); await refresh(); }
  async function retire(creditId,amount,beneficiary){ await apiPost(`/market/credits/${creditId}/retire`,{amount,beneficiary}); note('Credits retired and certificate generated.'); await refresh(); }
  const props={page,setPage,role,setRole,user,health,projects,credits,listings,auditors,project,selected,setSelected,stats,submitProject,hireAuditor,approve,reject,requestInfo,listCredit,buy,retire,note,refresh,loading}
  if(!user) return <div className="app-shell no-sidebar"><main className="workspace full-workspace"><AuthPage login={login} register={register} health={health}/>{toast&&<Toast msg={toast}/>}</main></div>
  return <div className="app-shell"><Sidebar {...{page,setPage,role,setRole,mobile,setMobile,logout}}/><div className="content-shell"><Topbar {...{user,drawer,setDrawer,setMobile,health,refresh}}/><main className="workspace">{page==='dashboard'&&<Dashboard {...props}/>} {page==='submit'&&<Submit {...props}/>} {page==='projects'&&<Projects {...props}/>} {page==='details'&&project&&<Details {...props}/>} {page==='auditors'&&<Auditors {...props}/>} {page==='auditor'&&<AuditorQueue {...props}/>} {page==='review'&&project&&<Review {...props}/>} {page==='wallet'&&<WalletPage {...props}/>} {page==='marketplace'&&<Marketplace {...props}/>} {page==='admin'&&<Admin {...props}/>} {page==='settings'&&<SettingsPage {...props}/>}</main></div>{drawer&&<Notifications setDrawer={setDrawer} health={health}/>} {toast&&<Toast msg={toast}/>}</div>
}

function Toast({msg}){return <div className="toast"><Check size={16}/>{msg}</div>}
function Sidebar({page,setPage,role,setRole,mobile,setMobile,logout}){ return <><aside className={`sidebar ${mobile?'sidebar-open':''}`}><button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button><div className="brand"><div className="brand-mark"><Leaf size={22}/></div><div><h1>CarbonLedger</h1><p>Institutional Grade</p></div></div><div className="role-switch">{['user','auditor','admin'].map(r=><button key={r} className={role===r?'active':''} onClick={()=>setRole(r)}>{r}</button>)}</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'nav-link nav-active':'nav-link'} onClick={()=>{setPage(key);setMobile(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-footer"><button className="primary full" onClick={()=>setPage('submit')}><Plus size={16}/>New Project</button><button className="nav-link" onClick={()=>setPage('settings')}><Settings size={18}/>Settings</button><button className="nav-link" onClick={logout}><LogOut size={18}/>Logout</button></div></aside>{mobile&&<button className="nav-backdrop" onClick={()=>setMobile(false)}/>}</> }
function Topbar({user,drawer,setDrawer,setMobile,health,refresh}){ return <header className="topbar"><button className="icon menu" onClick={()=>setMobile(true)}><Menu size={18}/></button><div className="searchbox"><Search size={16}/><input placeholder="Search projects, auditors, credits, tx hashes..."/></div><div className="topbar-actions"><button className="icon" onClick={refresh}><Gauge size={18}/></button><button className="icon" onClick={()=>setDrawer(!drawer)}><Bell size={18}/><span className="dot"/></button><span className={health?.blockchain?'badge success':'badge warning'}>{health?.blockchain?'CHAIN':'NO CHAIN'}</span><button className="wallet connected"><Wallet size={16}/>{user.walletAddress?.slice(0,6)}...{user.walletAddress?.slice(-4)}</button><div className="avatar">{user.name?.[0]?.toUpperCase()}</div></div></header> }
function Header({eyebrow,title,desc,action}){ return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{desc}</p></div>{action}</div> }
function PanelTitle({icon:Icon,title,action}){ return <div className="panel-title"><div><Icon size={18}/><h3>{title}</h3></div><span>{action}</span></div> }
function Stat({icon:Icon,label,value,help}){ return <section className="stat"><div className="stat-icon"><Icon size={18}/></div><p>{label}</p><strong>{value}</strong><span>{help}</span></section> }
function Metric({label,value,mono}){ return <div className="metric"><span>{label}</span><strong className={mono?'mono':''}>{value || '-'}</strong></div> }
function Field({label,children}){ return <label className="field"><span>{label}</span>{children}</label> }
function Empty({title,body}){ return <div className="doc"><AlertTriangle size={32}/><strong>{title}</strong><p>{body}</p></div> }
function Table({cols,rows}){ return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={cols.length}><Empty title="No records yet" body="Create records through the application flow and they will appear here from MongoDB."/></td></tr>}</tbody></table></div> }

function AuthPage({login,register}){ const [mode,setMode]=React.useState('login'); const [form,setForm]=React.useState({name:'',email:'',password:'',role:'user',walletAddress:'',orgName:'',orgType:''}); const [error,setError]=React.useState(''); const upd=(k,v)=>setForm({...form,[k]:v}); async function submit(e){e.preventDefault();setError('');try{mode==='login'?await login(form):await register(form)}catch(err){setError(errMsg(err))}} return <div className="login-page"><section className="login-card"><div className="brand compact"><div className="brand-mark"><Leaf size={22}/></div><div><h1>CarbonLedger</h1><p>Mongo + JWT + Blockchain</p></div></div><h2>{mode==='login'?'Sign in':'Create account'}</h2><p>Use a real Mongo-backed account. Wallet address is required for on-chain project ownership.</p><form className="form" onSubmit={submit}>{mode==='register'&&<Field label="Name"><input value={form.name} onChange={e=>upd('name',e.target.value)} required/></Field>}<Field label="Email"><input type="email" value={form.email} onChange={e=>upd('email',e.target.value)} required/></Field><Field label="Password"><input type="password" value={form.password} onChange={e=>upd('password',e.target.value)} required/></Field>{mode==='register'&&<><Field label="Role"><select value={form.role} onChange={e=>upd('role',e.target.value)}><option value="user">Project Owner</option><option value="auditor">Auditor</option></select></Field><Field label="Wallet Address"><input value={form.walletAddress} onChange={e=>upd('walletAddress',e.target.value)} placeholder="0x..." required/></Field><Field label="Organization"><input value={form.orgName} onChange={e=>upd('orgName',e.target.value)}/></Field></>}{error&&<p className="error-text">{error}</p>}<button className="primary full">{mode==='login'?'Login':'Register'}</button><button type="button" className="secondary full" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create account':'Back to login'}</button></form></section></div> }
function Dashboard({stats,projects,credits,setPage,setSelected,health}){ return <div className="stack"><Header eyebrow="Connected Workspace" title="CarbonLedger Dashboard" desc="Data is loaded from MongoDB and lifecycle actions call the backend, which relays registry transactions to the blockchain." action={<button className="primary" onClick={()=>setPage('submit')}><Plus size={16}/>Submit Project</button>}/><div className="stats-grid"><Stat icon={BriefcaseBusiness} label="Total Projects" value={stats.total} help={`${stats.active} active`}/><Stat icon={Coins} label="Credits Issued" value={fmt(stats.issued)} help="Mongo credit records"/><Stat icon={Store} label="Open Listings" value={fmt(stats.listed)} help="marketplace supply"/><Stat icon={Recycle} label="Retired" value={fmt(stats.retired)} help="retirement records"/></div><div className="grid"><section className="panel span8"><PanelTitle icon={ListChecks} title="Project Lifecycle" action={health?.blockchain?'Chain configured':'Chain missing'}/>{projects.length?<div className="timeline">{projects.map(p=><button className="timeline-item" key={p.projectId} onClick={()=>{setSelected(p.projectId);setPage('details')}}><span className="timeline-dot"/><div><strong>{p.title}</strong><p>{p.lastComment || `${p.type} project in ${p.location}`}</p></div><span className={badge(p.status)}>{p.status}</span></button>)}</div>:<Empty title="No projects in MongoDB" body="Submit a project to create a database record and on-chain registry entry."/>}</section><section className="panel span4"><PanelTitle icon={BarChart3} title="Credit Curve" action="Live"/><div className="bar-chart">{[20,35,50,65,80,55,stats.issued?90:25].map((h,i)=><span key={i} style={{height:`${h}%`}}/> )}</div><div className="split"><span>Issued supply</span><strong>{fmt(stats.issued)}</strong></div></section></div><section className="panel"><PanelTitle icon={Wallet} title="Recent Credits" action="Mongo wallet"/><CreditsTable credits={credits}/></section></div> }
function Submit({submitProject,user}){ const [f,setF]=React.useState({title:'',type:'Solar',location:'',creditsRequested:'',description:'',methodology:'',ownerWallet:user.walletAddress}); const [error,setError]=React.useState(''); const upd=(k,v)=>setF({...f,[k]:v}); async function submit(e){e.preventDefault();setError('');try{await submitProject(f)}catch(err){setError(errMsg(err))}} return <div className="stack"><Header eyebrow="Projects / New Registration" title="Submit New Project" desc="This creates a Mongo project and calls CarbonRegistry.submitProjectForOwner through the backend relayer." action={<span className="badge info">CHAIN REQUIRED</span>}/><form className="grid" onSubmit={submit}><section className="panel span8 form"><PanelTitle icon={Building2} title="Project Details" action="Required"/><div className="field-grid"><Field label="Project Name"><input value={f.title} onChange={e=>upd('title',e.target.value)} required/></Field><Field label="Project Type"><select value={f.type} onChange={e=>upd('type',e.target.value)}>{['Solar','Wind','Reforestation','Biomass','Hydro','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Location"><input value={f.location} onChange={e=>upd('location',e.target.value)} required/></Field><Field label="Requested Credits"><input type="number" value={f.creditsRequested} onChange={e=>upd('creditsRequested',e.target.value)} required/></Field></div><Field label="Project Description"><textarea rows="5" value={f.description} onChange={e=>upd('description',e.target.value)} required/></Field><div className="field-grid"><Field label="Methodology"><input value={f.methodology} onChange={e=>upd('methodology',e.target.value)}/></Field><Field label="Owner Wallet"><input value={f.ownerWallet} onChange={e=>upd('ownerWallet',e.target.value)} required/></Field></div>{error&&<p className="error-text">{error}</p>}</section><section className="panel span4 form"><PanelTitle icon={CloudUpload} title="Evidence Package" action="Optional upload"/>{['PDD / Methodology','Monitoring Evidence','Site Images'].map(x=><div className="upload" key={x}><Upload size={18}/><div><strong>{x}</strong><p>Upload endpoint is ready through multipart project create.</p></div></div>)}<button className="primary full" type="submit">Register On-Chain</button></section></form></div> }
function Projects({projects,setPage,setSelected}){ return <div className="stack"><Header eyebrow="Owner Registry" title="My Projects" desc="Projects are fetched from /api/projects according to your JWT role." action={<button className="secondary"><Filter size={16}/>Filter</button>}/><section className="panel"><div className="toolbar"><div className="searchbox table-search"><Search size={16}/><input placeholder="Search by project, status, location..."/></div><button className="secondary"><SlidersHorizontal size={16}/>Advanced</button></div><Table cols={['Project','On-chain ID','Credits','Auditor','Status','Action']} rows={projects.map(p=>[<div><strong>{p.title}</strong><p className="muted">{p.projectId} - {p.location}</p></div>,p.onChainProjectId || '-',`${fmt(p.creditsApproved||p.creditsRequested)} ${p.creditsApproved?'approved':'requested'}`,p.assignedAuditor?.name || 'Unassigned',<span className={badge(p.status)}>{p.status}</span>,<button className="link" onClick={()=>{setSelected(p.projectId);setPage('details')}}>View <ChevronRight size={14}/></button>])}/></section></div> }
function Details({project,setPage}){ return <div className="stack"><Header eyebrow={`Project / ${project.projectId}`} title={project.title} desc={`${project.type} project in ${project.location}. Mongo ID maps to on-chain project ${project.onChainProjectId || '-'}.`} action={<span className={badge(project.status)}>{project.status}</span>}/><div className="grid"><section className="panel span8"><PanelTitle icon={Gauge} title="Audit Timeline" action={project.approvalHash||project.chainHash||'No tx yet'}/>{[['Project Submitted',project.createdAt,'Mongo + contract registry entry created.'],['Auditor Assignment',project.assignedAuditor?.name || 'Unassigned',project.assignedAuditorWallet || 'Waiting for assignment.'],['Verification Decision',project.status,project.lastComment],['On-chain ID',project.onChainProjectId || 'Pending','Stored in Mongo after registry transaction.']].map((x,i)=><div className="step" key={x[0]}><span>{i+1}</span><div><strong>{x[0]}</strong><p>{x[1] || '-'}</p><small>{x[2]}</small></div></div>)}</section><section className="panel span4"><PanelTitle icon={Coins} title="Credit Decision" action="MRV"/><Metric label="Requested" value={fmt(project.creditsRequested)}/><Metric label="Approved" value={fmt(project.creditsApproved)}/><Metric label="Owner Wallet" value={project.ownerWallet} mono/><Metric label="Chain Hash" value={project.chainHash} mono/><button className="primary full" onClick={()=>setPage('auditors')}><UserCheck size={16}/>Hire Auditor</button></section></div></div> }
function Auditors({projects,auditors,selected,setSelected,hireAuditor,setPage}){ const [auditor,setAuditor]=React.useState(''); return <div className="stack"><Header eyebrow="Verification Network" title="Hire Auditor" desc="Auditors come from Mongo users with role=auditor. Assignment is relayed to CarbonRegistry.assignAuditor." action={<select className="compact" value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option key={p.projectId} value={p.projectId}>{p.title}</option>)}</select>}/><section className="panel form"><PanelTitle icon={UserCheck} title="Assign Auditor" action={`${auditors.length} auditors`}/>{projects.length&&auditors.length?<><Field label="Auditor"><select value={auditor} onChange={e=>setAuditor(e.target.value)} required><option value="">Select auditor</option>{auditors.map(a=><option key={a._id} value={a._id}>{a.name} - {a.walletAddress}</option>)}</select></Field><button className="primary" disabled={!auditor || !selected} onClick={async()=>{await hireAuditor(selected,auditor);setPage('projects')}}>Assign On-Chain</button></>:<Empty title="Need project and auditor records" body="Register an auditor account and submit a project first."/>}</section></div> }
function AuditorQueue({projects,setPage,setSelected}){ return <div className="stack"><Header eyebrow="Auditor Workspace" title="Verification Queue" desc="Assigned projects loaded by JWT role from /api/audit/assigned." action={<span className="badge info">{projects.length} Records</span>}/><section className="panel"><PanelTitle icon={ListChecks} title="Assigned Projects" action="Mongo"/><div className="queue">{projects.length?projects.map(p=><button className="queue-card" key={p.projectId} onClick={()=>{setSelected(p.projectId);setPage('review')}}><div><strong>{p.title}</strong><p>{p.location} - {fmt(p.creditsRequested)} requested credits</p></div><span className={badge(p.status)}>{p.status}</span><ChevronRight size={18}/></button>):<Empty title="No assigned projects" body="Hire an auditor from the owner/admin account first."/>}</div></section></div> }
function Review({project,approve,reject,requestInfo}){ const [amount,setAmount]=React.useState(project.creditsApproved||project.creditsRequested); const [reason,setReason]=React.useState('Evidence package needs additional baseline documents.'); React.useEffect(()=>setAmount(project.creditsApproved||project.creditsRequested),[project.projectId]); return <div className="stack"><Header eyebrow={`Audit Workspace / ${project.projectId}`} title={project.title} desc="Approve/reject/more-info calls backend audit routes and updates contract + Mongo." action={<span className={badge(project.status)}>{project.status}</span>}/><div className="grid"><section className="panel span8"><PanelTitle icon={FileText} title="Evidence Viewer" action="Mongo files"/><div className="doc"><FileCheck2 size={42}/><strong>{project.files?.length || 0} uploaded files</strong><p>{project.description}</p></div></section><section className="panel span4 form"><PanelTitle icon={ClipboardCheck} title="Audit Decision" action="JWT protected"/><Field label="Approved Credits"><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Reason / Notes"><textarea rows="5" value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className="primary full" onClick={()=>approve(project.projectId,amount)}>Approve and Mint</button><button className="secondary full" onClick={()=>requestInfo(project.projectId,reason)}>Request More Info</button><button className="danger full" onClick={()=>reject(project.projectId,reason)}>Reject Project</button></section></div></div> }
function WalletPage({credits,listCredit,retire}){ const [id,setId]=React.useState(''); const c=credits.find(x=>x.creditId===id)||credits[0]; return <div className="stack"><Header eyebrow="Token Holdings" title="Carbon Credits Wallet" desc="Credits are Mongo records created after successful registry mint transactions." action={<span className="badge market">JWT WALLET</span>}/><section className="panel"><PanelTitle icon={Wallet} title="Owned Credits" action={`${credits.length} batches`}/><CreditsTable credits={credits} select={setId}/></section>{c&&<div className="grid"><section className="panel span6"><PanelTitle icon={Store} title="List Credits for Sale" action={c.creditId}/><CreditForm button="Create Listing" onSubmit={(a,p)=>listCredit(c.creditId,a,p)} price={25} max={c.available}/></section><section className="panel span6"><PanelTitle icon={Recycle} title="Retire Credits" action="Certificate"/><CreditForm button="Generate Retirement" onSubmit={(a)=>retire(c.creditId,a,'Retirement beneficiary')} max={c.available} retire/></section></div>}</div> }
function CreditsTable({credits,select}){ return <Table cols={['Credit','Project','Amount','Available','Listed','Retired','Status']} rows={credits.map(c=>[<button className="link" onClick={()=>select?.(c.creditId)}>{c.creditId}</button>,c.project?.title || c.project?.projectId || '-',fmt(c.amount),fmt(c.available),fmt(c.listed),fmt(c.retired),<span className={badge(c.status)}>{c.status}</span>])}/> }
function CreditForm({button,onSubmit,price=0,max=0,retire}){ const [a,setA]=React.useState(''), [p,setP]=React.useState(price); return <form className="form" onSubmit={e=>{e.preventDefault();onSubmit(a,p)}}><Field label="Amount"><input type="number" min="1" max={max} value={a} onChange={e=>setA(e.target.value)} required/></Field>{!retire&&<Field label="Price per Credit"><input type="number" step="0.1" value={p} onChange={e=>setP(e.target.value)} required/></Field>}<div className="split"><span>{retire?'Retiring':'Total value'}</span><strong>{retire?`${fmt(Number(a))} credits`:money(Number(a)*Number(p))}</strong></div><button className={retire?'secondary full':'primary full'}>{button}</button></form> }
function Marketplace({listings,buy}){ return <div className="stack"><Header eyebrow="Market" title="Carbon Credit Marketplace" desc="Open listings are loaded from MongoDB and purchases create buyer credit records." action={<button className="secondary"><Filter size={16}/>Filters</button>}/><div className="market-stats"><Metric label="Open Supply" value={fmt(listings.reduce((s,l)=>s+l.amount,0))}/><Metric label="Open Listings" value={listings.length}/><Metric label="Avg Price" value={listings.length?money(listings.reduce((s,l)=>s+l.price,0)/listings.length):'$0.00'}/><Metric label="Source" value="Mongo"/></div><div className="cards three">{listings.length?listings.map(l=><section className="panel listing" key={l.listingId}><div className="listing-top"><span className={badge(l.status)}>{l.status}</span><code>{l.listingId}</code></div><h3>{l.credit?.project?.title || 'Credit listing'}</h3><p>{l.seller?.name}</p><div className="listing-meta"><span><Globe2 size={15}/>{l.credit?.project?.location || '-'}</span><span><Leaf size={15}/>{l.credit?.project?.type || '-'}</span></div><div className="price"><div><small>Amount</small><strong>{fmt(l.amount)}</strong></div><div><small>Price/Credit</small><strong>{money(l.price)}</strong></div></div><button className="primary full" onClick={()=>buy(l.listingId)}><ShoppingCart size={16}/>Buy Credits</button></section>):<section className="panel"><Empty title="No open listings" body="List credits from the wallet to populate the marketplace."/></section>}</div></div> }
function Admin({projects,credits,auditors,health}){ return <div className="stack"><Header eyebrow="Platform Control" title="Admin Dashboard" desc="Operational view of Mongo, JWT accounts, and blockchain configuration." action={<span className={health?.blockchain?'badge success':'badge warning'}>{health?.blockchain?'CHAIN READY':'CHAIN MISSING'}</span>}/><div className="stats-grid"><Stat icon={Building2} label="Projects" value={projects.length} help="registry records"/><Stat icon={UserCheck} label="Auditors" value={auditors.length} help="verified network"/><Stat icon={Coins} label="Credits" value={fmt(credits.reduce((s,c)=>s+c.amount,0))} help="issued supply"/><Stat icon={AlertTriangle} label="Mongo Env" value={health?.mongo?'Yes':'No'} help="MONGODB_URI"/></div><section className="panel"><PanelTitle icon={ShieldCheck} title="Governance Checks" action="Live config"/><div className="admin-grid">{['JWT auth enabled','MongoDB persistence','Registry relayer configured','Auditor wallets required','On-chain project IDs stored','Marketplace balances tracked'].map(x=><div className="admin-task" key={x}><Lock size={16}/>{x}<ChevronRight size={16}/></div>)}</div></section></div> }
function SettingsPage({user,health,refresh}){ return <div className="stack"><Header eyebrow="Account" title="Settings" desc="Session and connection status." action={<button className="secondary" onClick={refresh}>Refresh</button>}/><div className="grid"><section className="panel span6"><PanelTitle icon={Settings} title="Profile" action={user.role}/><Metric label="Name" value={user.name}/><Metric label="Email" value={user.email}/><Metric label="Wallet" value={user.walletAddress} mono/></section><section className="panel span6"><PanelTitle icon={Gauge} title="Connection Health" action="Backend"/><Metric label="Mongo" value={health?.mongo?'Configured':'Missing'}/><Metric label="Blockchain" value={health?.blockchain?'Configured':'Missing'}/><Metric label="Data Mode" value="API only"/></section></div></div> }
function Notifications({setDrawer,health}){ return <aside className="drawer"><div className="drawer-head"><h3>Notifications</h3><button className="icon" onClick={()=>setDrawer(false)}><X size={18}/></button></div>{[['Backend',health?.ok?'API health endpoint responding':'Check backend server'],['MongoDB',health?.mongo?'MONGODB_URI configured':'MONGODB_URI missing'],['Blockchain',health?.blockchain?'Relayer configured':'RPC/private key/contract missing']].map(i=><div className="notice" key={i[0]}><strong>{i[0]}</strong><p>{i[1]}</p></div>)}</aside> }
